gitfs_remotes:
  - https://github.com/saltstack-formulas/nginx-formula.git
  - https://github.com/saltstack-formulas/users-formula.git
  - https://github.com/saltstack-formulas/rsyslog-formula.git
  - https://github.com/saltstack-formulas/memcached-formula.git
  - https://github.com/elastic-coders/saltstack-uwsgi-ng-formula.git
